-- combining data.
use `CASE_STUDY1`;
DROP TABLE IF EXISTS COMBINED_DATA;
-- combining 12 months data into single table containing all data from Jan 2022 to Dec 2022 and Jan 2023 to May 2023

CREATE TABLE  COMBINED_DATA AS (
	SELECT * FROM  `CASE_STUDY1`.`TRIP_DATA_2025_JAN`
    UNION ALL
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_FEB`
    UNION ALL
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_MAR`
    UNION ALL 
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_APR`
    UNION ALL 
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_MAY`
    UNION ALL 
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_JUN`
    UNION ALL 
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_JUL`
    UNION ALL 
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_AUG`
    UNION ALL
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_SEP`
    UNION ALL
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_OCT`
    UNION ALL
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_NOV`
    UNION ALL
    SELECT * FROM `CASE_STUDY1`.`TRIP_DATA_2025_DEC`
);
 
SELECT COUNT(*) FROM `COMBINED_DATA`;